# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18_B3CSQCeV0dshEGrjkXG4G6dTsvl4rv
"""

import pickle

with open('heart_predict.pkl','rb') as file:
  clf=pickle.load(file)

prediction = clf.predict([[	1.000000,-0.103240,-0.071966,0.271121,0.219823,0.121243,-0.132696,-0.390227,0.088163,0.208137,-0.169105,0.271551,0.072297]])

prediction

prediction=clf.predict([[47,1,0,110,275,0,0,118,1,1.0,1,1,2]])

prediction
